package example.model;

import java.util.Date;

public class THomechargeOrderOperationRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_homecharge_order_operation_record.id
     *
     * @mbg.generated Tue Apr 19 21:12:09 CST 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_homecharge_order_operation_record.homecharge_order_id
     *
     * @mbg.generated Tue Apr 19 21:12:09 CST 2022
     */
    private Long homechargeOrderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_homecharge_order_operation_record.order_no
     *
     * @mbg.generated Tue Apr 19 21:12:09 CST 2022
     */
    private String orderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_homecharge_order_operation_record.node_code
     *
     * @mbg.generated Tue Apr 19 21:12:09 CST 2022
     */
    private String nodeCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_homecharge_order_operation_record.node_name
     *
     * @mbg.generated Tue Apr 19 21:12:09 CST 2022
     */
    private String nodeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_homecharge_order_operation_record.task_id
     *
     * @mbg.generated Tue Apr 19 21:12:09 CST 2022
     */
    private String taskId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_homecharge_order_operation_record.operation_code
     *
     * @mbg.generated Tue Apr 19 21:12:09 CST 2022
     */
    private String operationCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_homecharge_order_operation_record.operation_name
     *
     * @mbg.generated Tue Apr 19 21:12:09 CST 2022
     */
    private String operationName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_homecharge_order_operation_record.operation_form_content
     *
     * @mbg.generated Tue Apr 19 21:12:09 CST 2022
     */
    private String operationFormContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_homecharge_order_operation_record.is_deleted
     *
     * @mbg.generated Tue Apr 19 21:12:09 CST 2022
     */
    private Byte isDeleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_homecharge_order_operation_record.create_time
     *
     * @mbg.generated Tue Apr 19 21:12:09 CST 2022
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_homecharge_order_operation_record.update_time
     *
     * @mbg.generated Tue Apr 19 21:12:09 CST 2022
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_homecharge_order_operation_record.create_by
     *
     * @mbg.generated Tue Apr 19 21:12:09 CST 2022
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_homecharge_order_operation_record.update_by
     *
     * @mbg.generated Tue Apr 19 21:12:09 CST 2022
     */
    private String updateBy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_homecharge_order_operation_record.id
     *
     * @return the value of t_homecharge_order_operation_record.id
     *
     * @mbg.generated Tue Apr 19 21:12:09 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_homecharge_order_operation_record.id
     *
     * @param id the value for t_homecharge_order_operation_record.id
     *
     * @mbg.generated Tue Apr 19 21:12:09 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_homecharge_order_operation_record.homecharge_order_id
     *
     * @return the value of t_homecharge_order_operation_record.homecharge_order_id
     *
     * @mbg.generated Tue Apr 19 21:12:09 CST 2022
     */
    public Long getHomechargeOrderId() {
        return homechargeOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_homecharge_order_operation_record.homecharge_order_id
     *
     * @param homechargeOrderId the value for t_homecharge_order_operation_record.homecharge_order_id
     *
     * @mbg.generated Tue Apr 19 21:12:09 CST 2022
     */
    public void setHomechargeOrderId(Long homechargeOrderId) {
        this.homechargeOrderId = homechargeOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_homecharge_order_operation_record.order_no
     *
     * @return the value of t_homecharge_order_operation_record.order_no
     *
     * @mbg.generated Tue Apr 19 21:12:09 CST 2022
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_homecharge_order_operation_record.order_no
     *
     * @param orderNo the value for t_homecharge_order_operation_record.order_no
     *
     * @mbg.generated Tue Apr 19 21:12:09 CST 2022
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_homecharge_order_operation_record.node_code
     *
     * @return the value of t_homecharge_order_operation_record.node_code
     *
     * @mbg.generated Tue Apr 19 21:12:09 CST 2022
     */
    public String getNodeCode() {
        return nodeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_homecharge_order_operation_record.node_code
     *
     * @param nodeCode the value for t_homecharge_order_operation_record.node_code
     *
     * @mbg.generated Tue Apr 19 21:12:09 CST 2022
     */
    public void setNodeCode(String nodeCode) {
        this.nodeCode = nodeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_homecharge_order_operation_record.node_name
     *
     * @return the value of t_homecharge_order_operation_record.node_name
     *
     * @mbg.generated Tue Apr 19 21:12:09 CST 2022
     */
    public String getNodeName() {
        return nodeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_homecharge_order_operation_record.node_name
     *
     * @param nodeName the value for t_homecharge_order_operation_record.node_name
     *
     * @mbg.generated Tue Apr 19 21:12:09 CST 2022
     */
    public void setNodeName(String nodeName) {
        this.nodeName = nodeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_homecharge_order_operation_record.task_id
     *
     * @return the value of t_homecharge_order_operation_record.task_id
     *
     * @mbg.generated Tue Apr 19 21:12:09 CST 2022
     */
    public String getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_homecharge_order_operation_record.task_id
     *
     * @param taskId the value for t_homecharge_order_operation_record.task_id
     *
     * @mbg.generated Tue Apr 19 21:12:09 CST 2022
     */
    public void setTaskId(String taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_homecharge_order_operation_record.operation_code
     *
     * @return the value of t_homecharge_order_operation_record.operation_code
     *
     * @mbg.generated Tue Apr 19 21:12:09 CST 2022
     */
    public String getOperationCode() {
        return operationCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_homecharge_order_operation_record.operation_code
     *
     * @param operationCode the value for t_homecharge_order_operation_record.operation_code
     *
     * @mbg.generated Tue Apr 19 21:12:09 CST 2022
     */
    public void setOperationCode(String operationCode) {
        this.operationCode = operationCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_homecharge_order_operation_record.operation_name
     *
     * @return the value of t_homecharge_order_operation_record.operation_name
     *
     * @mbg.generated Tue Apr 19 21:12:09 CST 2022
     */
    public String getOperationName() {
        return operationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_homecharge_order_operation_record.operation_name
     *
     * @param operationName the value for t_homecharge_order_operation_record.operation_name
     *
     * @mbg.generated Tue Apr 19 21:12:09 CST 2022
     */
    public void setOperationName(String operationName) {
        this.operationName = operationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_homecharge_order_operation_record.operation_form_content
     *
     * @return the value of t_homecharge_order_operation_record.operation_form_content
     *
     * @mbg.generated Tue Apr 19 21:12:09 CST 2022
     */
    public String getOperationFormContent() {
        return operationFormContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_homecharge_order_operation_record.operation_form_content
     *
     * @param operationFormContent the value for t_homecharge_order_operation_record.operation_form_content
     *
     * @mbg.generated Tue Apr 19 21:12:09 CST 2022
     */
    public void setOperationFormContent(String operationFormContent) {
        this.operationFormContent = operationFormContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_homecharge_order_operation_record.is_deleted
     *
     * @return the value of t_homecharge_order_operation_record.is_deleted
     *
     * @mbg.generated Tue Apr 19 21:12:09 CST 2022
     */
    public Byte getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_homecharge_order_operation_record.is_deleted
     *
     * @param isDeleted the value for t_homecharge_order_operation_record.is_deleted
     *
     * @mbg.generated Tue Apr 19 21:12:09 CST 2022
     */
    public void setIsDeleted(Byte isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_homecharge_order_operation_record.create_time
     *
     * @return the value of t_homecharge_order_operation_record.create_time
     *
     * @mbg.generated Tue Apr 19 21:12:09 CST 2022
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_homecharge_order_operation_record.create_time
     *
     * @param createTime the value for t_homecharge_order_operation_record.create_time
     *
     * @mbg.generated Tue Apr 19 21:12:09 CST 2022
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_homecharge_order_operation_record.update_time
     *
     * @return the value of t_homecharge_order_operation_record.update_time
     *
     * @mbg.generated Tue Apr 19 21:12:09 CST 2022
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_homecharge_order_operation_record.update_time
     *
     * @param updateTime the value for t_homecharge_order_operation_record.update_time
     *
     * @mbg.generated Tue Apr 19 21:12:09 CST 2022
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_homecharge_order_operation_record.create_by
     *
     * @return the value of t_homecharge_order_operation_record.create_by
     *
     * @mbg.generated Tue Apr 19 21:12:09 CST 2022
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_homecharge_order_operation_record.create_by
     *
     * @param createBy the value for t_homecharge_order_operation_record.create_by
     *
     * @mbg.generated Tue Apr 19 21:12:09 CST 2022
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_homecharge_order_operation_record.update_by
     *
     * @return the value of t_homecharge_order_operation_record.update_by
     *
     * @mbg.generated Tue Apr 19 21:12:09 CST 2022
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_homecharge_order_operation_record.update_by
     *
     * @param updateBy the value for t_homecharge_order_operation_record.update_by
     *
     * @mbg.generated Tue Apr 19 21:12:09 CST 2022
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }
}